travis:
  secure:
    BINSTAR_TOKEN: zcOMgtEhlbkV2J4PMtBt9eovoxpTEEdsfJP/n88vaROfNBZoPxsk2oy6lGMuMmV1n45BNJhWO3ABfuHqfCi16jUdwHyzodif5UE1leAwWkK5kSpmAUwtx+dJ4fMo5hztELmGA1R247dxFk3fe3VIs1beJiQ3/EKfNMAQHJESBrLtuz0b/7xGek+37cd/NObwVooACK4JIuJsbLbJqOiUtobRr/L1/OTGuRgZ+eKTE/hit76vQ3TcWXuPo8YrFn4mzg6ePZrrelDWUdfEdgYJq7arh5rntXqtksQqai0/B0Y23oxzrWZUoEdtAfOTJv4wOlbIjGNT7lOffB3oi5cfJxhYlyR5Iv02GOY45PKKwOVKrBavt/X76/SDOXdkzKqqr+wQ4Prff6bb1XwE6sH2xdoAhASML5Piq2D/FSfEdsy0kW7+Oy8P0FhPS1/7+dhCRHWex1GWLrLIOV92+093Y09PAAaMghvuHuUml/yMoaHuM1CCvOfgZT6clOSglVyYUpFbbt0GMeN4TG+CaN5r4vqDNDEEpHPcagfiq3nh8w2bMQQ6kEp8flkwlTFWHlKI4Jr0KmCHUj1Ah26qDLXT7IZofm9H8+rEXqfU4ZMRhewT7b5j2ZWc8I/qTDENtU3p76XNMNsIMVM9ev55ECxDMFqcfasPpEE6ALmgimvAqFU=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
